name: Debans Network metrics
on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  debans-network-organization-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Debans Network Organization
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: profile/metrics/metrics.svg
          user: debans-network
          base: header, metadata, repositories, community, activity
          config_display: columns
          config_order: base.header, base.metadata, base.repositories, base.community, base.activity, introduction, repositories
          plugin_lines: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_traffic: yes
          config_timezone: Europe/Paris
