name: Debans Network metrics
on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  debans-network-organization-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Debans Network Organization
        uses: lowlighter/metrics@latest
        with:
          #token: ${{ secrets.METRICS_TOKEN }}
          filename: profile/metrics/metrics.svg
          user: debans-network
          base: header
          config_display: columns
          config_order: base.header, introduction, habits, people, pagespeed
          plugin_lines: yes
          plugin_introduction: yes
          plugin_introduction_title: no
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Europe/Paris
          plugin_people: yes
          plugin_people_types: members,followers
          #plugin_people_thanks: ,thanks
          plugin_pagespeed: no
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://debans.network
